//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.wsfmis {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsfmis.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTransactions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getTransactions(string dvno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getTransactionsAsync(string dvno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTransactions_byBatchno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getTransactions_byBatchno(long batchno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTransactions_byBatchno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getTransactions_byBatchnoAsync(long batchno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_login_parameter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string get_login_parameter(string email, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_login_parameter", ReplyAction="*")]
        System.Threading.Tasks.Task<string> get_login_parameterAsync(string email, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/send_sms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string send_sms(string sendTo, string msg, int isid, int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/send_sms", ReplyAction="*")]
        System.Threading.Tasks.Task<string> send_smsAsync(string sendTo, string msg, int isid, int priority);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WebAOMS.wsfmis.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WebAOMS.wsfmis.WebServiceSoap>, WebAOMS.wsfmis.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet getTransactions(string dvno) {
            return base.Channel.getTransactions(dvno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getTransactionsAsync(string dvno) {
            return base.Channel.getTransactionsAsync(dvno);
        }
        
        public System.Data.DataSet getTransactions_byBatchno(long batchno) {
            return base.Channel.getTransactions_byBatchno(batchno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getTransactions_byBatchnoAsync(long batchno) {
            return base.Channel.getTransactions_byBatchnoAsync(batchno);
        }
        
        public string get_login_parameter(string email, string pw) {
            return base.Channel.get_login_parameter(email, pw);
        }
        
        public System.Threading.Tasks.Task<string> get_login_parameterAsync(string email, string pw) {
            return base.Channel.get_login_parameterAsync(email, pw);
        }
        
        public string send_sms(string sendTo, string msg, int isid, int priority) {
            return base.Channel.send_sms(sendTo, msg, isid, priority);
        }
        
        public System.Threading.Tasks.Task<string> send_smsAsync(string sendTo, string msg, int isid, int priority) {
            return base.Channel.send_smsAsync(sendTo, msg, isid, priority);
        }
    }
}
