//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.ws_sms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws_sms.SMSWebServiceSoap")]
    public interface SMSWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebAOMS.ws_sms.HelloWorldResponse HelloWorld(WebAOMS.ws_sms.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAOMS.ws_sms.HelloWorldResponse> HelloWorldAsync(WebAOMS.ws_sms.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name sendTo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEND_SMS", ReplyAction="*")]
        WebAOMS.ws_sms.SEND_SMSResponse SEND_SMS(WebAOMS.ws_sms.SEND_SMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEND_SMS", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAOMS.ws_sms.SEND_SMSResponse> SEND_SMSAsync(WebAOMS.ws_sms.SEND_SMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebAOMS.ws_sms.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebAOMS.ws_sms.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAOMS.ws_sms.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebAOMS.ws_sms.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SEND_SMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SEND_SMS", Namespace="http://tempuri.org/", Order=0)]
        public WebAOMS.ws_sms.SEND_SMSRequestBody Body;
        
        public SEND_SMSRequest() {
        }
        
        public SEND_SMSRequest(WebAOMS.ws_sms.SEND_SMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SEND_SMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int isid;
        
        public SEND_SMSRequestBody() {
        }
        
        public SEND_SMSRequestBody(string sendTo, string msg, int isid) {
            this.sendTo = sendTo;
            this.msg = msg;
            this.isid = isid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SEND_SMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SEND_SMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAOMS.ws_sms.SEND_SMSResponseBody Body;
        
        public SEND_SMSResponse() {
        }
        
        public SEND_SMSResponse(WebAOMS.ws_sms.SEND_SMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SEND_SMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SEND_SMSResult;
        
        public SEND_SMSResponseBody() {
        }
        
        public SEND_SMSResponseBody(string SEND_SMSResult) {
            this.SEND_SMSResult = SEND_SMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSWebServiceSoapChannel : WebAOMS.ws_sms.SMSWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSWebServiceSoapClient : System.ServiceModel.ClientBase<WebAOMS.ws_sms.SMSWebServiceSoap>, WebAOMS.ws_sms.SMSWebServiceSoap {
        
        public SMSWebServiceSoapClient() {
        }
        
        public SMSWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAOMS.ws_sms.HelloWorldResponse WebAOMS.ws_sms.SMSWebServiceSoap.HelloWorld(WebAOMS.ws_sms.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebAOMS.ws_sms.HelloWorldRequest inValue = new WebAOMS.ws_sms.HelloWorldRequest();
            inValue.Body = new WebAOMS.ws_sms.HelloWorldRequestBody();
            WebAOMS.ws_sms.HelloWorldResponse retVal = ((WebAOMS.ws_sms.SMSWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAOMS.ws_sms.HelloWorldResponse> WebAOMS.ws_sms.SMSWebServiceSoap.HelloWorldAsync(WebAOMS.ws_sms.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAOMS.ws_sms.HelloWorldResponse> HelloWorldAsync() {
            WebAOMS.ws_sms.HelloWorldRequest inValue = new WebAOMS.ws_sms.HelloWorldRequest();
            inValue.Body = new WebAOMS.ws_sms.HelloWorldRequestBody();
            return ((WebAOMS.ws_sms.SMSWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAOMS.ws_sms.SEND_SMSResponse WebAOMS.ws_sms.SMSWebServiceSoap.SEND_SMS(WebAOMS.ws_sms.SEND_SMSRequest request) {
            return base.Channel.SEND_SMS(request);
        }
        
        public string SEND_SMS(string sendTo, string msg, int isid) {
            WebAOMS.ws_sms.SEND_SMSRequest inValue = new WebAOMS.ws_sms.SEND_SMSRequest();
            inValue.Body = new WebAOMS.ws_sms.SEND_SMSRequestBody();
            inValue.Body.sendTo = sendTo;
            inValue.Body.msg = msg;
            inValue.Body.isid = isid;
            WebAOMS.ws_sms.SEND_SMSResponse retVal = ((WebAOMS.ws_sms.SMSWebServiceSoap)(this)).SEND_SMS(inValue);
            return retVal.Body.SEND_SMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAOMS.ws_sms.SEND_SMSResponse> WebAOMS.ws_sms.SMSWebServiceSoap.SEND_SMSAsync(WebAOMS.ws_sms.SEND_SMSRequest request) {
            return base.Channel.SEND_SMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAOMS.ws_sms.SEND_SMSResponse> SEND_SMSAsync(string sendTo, string msg, int isid) {
            WebAOMS.ws_sms.SEND_SMSRequest inValue = new WebAOMS.ws_sms.SEND_SMSRequest();
            inValue.Body = new WebAOMS.ws_sms.SEND_SMSRequestBody();
            inValue.Body.sendTo = sendTo;
            inValue.Body.msg = msg;
            inValue.Body.isid = isid;
            return ((WebAOMS.ws_sms.SMSWebServiceSoap)(this)).SEND_SMSAsync(inValue);
        }
    }
}
