//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class fmisEntities : DbContext
    {
        public fmisEntities()
            : base("name=fmisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vw_Employee_Concatname> vw_Employee_Concatname { get; set; }
        public virtual DbSet<tbl_l_ChartOfAccountsParent> tbl_l_ChartOfAccountsParent { get; set; }
        public virtual DbSet<tbl_l_ChartOfAccounts> tbl_l_ChartOfAccounts { get; set; }
        public virtual DbSet<vw_PreAudit_Trans_Monitoring> vw_PreAudit_Trans_Monitoring { get; set; }
        public virtual DbSet<tbl_t_AccoutingEntries> tbl_t_AccoutingEntries { get; set; }
        public virtual DbSet<tbl_t_JEV_Details> tbl_t_JEV_Details { get; set; }
        public virtual DbSet<tblAMIS_Logtrans> tblAMIS_Logtrans { get; set; }
        public virtual DbSet<tbl_l_AddDataFromClaimant> tbl_l_AddDataFromClaimant { get; set; }
        public virtual DbSet<tbl_l_Fundtype> tbl_l_Fundtype { get; set; }
        public virtual DbSet<tblREF_AIS_Offices> tblREF_AIS_Offices { get; set; }
        public virtual DbSet<tbl_l_ChartOfAccountsChild> tbl_l_ChartOfAccountsChild { get; set; }
        public virtual DbSet<tbl_l_PayrollEmpStatus> tbl_l_PayrollEmpStatus { get; set; }
        public virtual DbSet<tbl_t_AccoutingEntries_CashFlow> tbl_t_AccoutingEntries_CashFlow { get; set; }
        public virtual DbSet<tbl_l_InformationSystem> tbl_l_InformationSystem { get; set; }
        public virtual DbSet<tbl_l_ChartOfAccounts_cashFlow> tbl_l_ChartOfAccounts_cashFlow { get; set; }
        public virtual DbSet<tbl_l_report_Signatory> tbl_l_report_Signatory { get; set; }
        public virtual DbSet<vw_username> vw_username { get; set; }
        public virtual DbSet<tbl_t_DocForm> tbl_t_DocForm { get; set; }
        public virtual DbSet<vw_search_field> vw_search_field { get; set; }
        public virtual DbSet<tbl_t_RAAOUP> tbl_t_RAAOUP { get; set; }
        public virtual DbSet<tbl_t_DV_Details> tbl_t_DV_Details { get; set; }
        public virtual DbSet<tblBMS_ObjectOfExpenditures> tblBMS_ObjectOfExpenditures { get; set; }
        public virtual DbSet<tbl_t_Oblig_Transaction> tbl_t_Oblig_Transaction { get; set; }
        public virtual DbSet<tbl_l_Persons_group> tbl_l_Persons_group { get; set; }
        public virtual DbSet<tbl_l_Address> tbl_l_Address { get; set; }
        public virtual DbSet<tbl_l_Persons> tbl_l_Persons { get; set; }
        public virtual DbSet<vw_AspNetUsers_details> vw_AspNetUsers_details { get; set; }
        public virtual DbSet<w_UserMenu> w_UserMenu { get; set; }
        public virtual DbSet<tbl_l_PayrollMapped> tbl_l_PayrollMapped { get; set; }
        public virtual DbSet<tbl_l_Transaction_ExpenseDetails> tbl_l_Transaction_ExpenseDetails { get; set; }
        public virtual DbSet<tbl_l_Transaction_DocumentList> tbl_l_Transaction_DocumentList { get; set; }
        public virtual DbSet<vw_Document_Status> vw_Document_Status { get; set; }
        public virtual DbSet<tbl_l_Transaction_CheckList> tbl_l_Transaction_CheckList { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<vw_Persons> vw_Persons { get; set; }
        public virtual DbSet<vw_t_Incoming_fromBudget> vw_t_Incoming_fromBudget { get; set; }
        public virtual DbSet<tbl_l_PMISOffice> tbl_l_PMISOffice { get; set; }
        public virtual DbSet<tbl_t_DocEvents_IPS> tbl_t_DocEvents_IPS { get; set; }
        public virtual DbSet<tbl_t_DocEvents_revision> tbl_t_DocEvents_revision { get; set; }
        public virtual DbSet<tbl_t_DocEvents_TargetParticipants> tbl_t_DocEvents_TargetParticipants { get; set; }
        public virtual DbSet<tbl_t_JEV_Audit_logs> tbl_t_JEV_Audit_logs { get; set; }
        public virtual DbSet<tblCMS_CDCheckBook_Audit_logs> tblCMS_CDCheckBook_Audit_logs { get; set; }
        public virtual DbSet<vw_docDetails_transaction> vw_docDetails_transaction { get; set; }
        public virtual DbSet<tbl_l_Transaction_type> tbl_l_Transaction_type { get; set; }
        public virtual DbSet<tbl_t_DocEvents> tbl_t_DocEvents { get; set; }
        public virtual DbSet<tbl_t_DocEvents_BudgetaryRequirements> tbl_t_DocEvents_BudgetaryRequirements { get; set; }
        public virtual DbSet<tbl_t_DocEvents_process_design> tbl_t_DocEvents_process_design { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
    
        [DbFunction("fmisEntities", "ufn_PreAudit_list")]
        public virtual IQueryable<ufn_PreAudit_list_Result> ufn_PreAudit_list(Nullable<byte> tstatus)
        {
            var tstatusParameter = tstatus.HasValue ?
                new ObjectParameter("Tstatus", tstatus) :
                new ObjectParameter("Tstatus", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_PreAudit_list_Result>("[fmisEntities].[ufn_PreAudit_list](@Tstatus)", tstatusParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_PreAudit_summary")]
        public virtual IQueryable<ufn_PreAudit_summary_Result> ufn_PreAudit_summary(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_PreAudit_summary_Result>("[fmisEntities].[ufn_PreAudit_summary](@from, @to)", fromParameter, toParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_PreAudit_Returned")]
        public virtual IQueryable<ufn_PreAudit_Returned_Result> ufn_PreAudit_Returned(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_PreAudit_Returned_Result>("[fmisEntities].[ufn_PreAudit_Returned](@from, @to)", fromParameter, toParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_PreAudit_Trans_Monitoring")]
        public virtual IQueryable<ufn_PreAudit_Trans_Monitoring_Result> ufn_PreAudit_Trans_Monitoring(Nullable<System.DateTime> from, Nullable<System.DateTime> to, Nullable<System.DateTime> tym)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var tymParameter = tym.HasValue ?
                new ObjectParameter("tym", tym) :
                new ObjectParameter("tym", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_PreAudit_Trans_Monitoring_Result>("[fmisEntities].[ufn_PreAudit_Trans_Monitoring](@from, @to, @tym)", fromParameter, toParameter, tymParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_PO_Trans_Monitoring")]
        public virtual IQueryable<ufn_PO_Trans_Monitoring_Result> ufn_PO_Trans_Monitoring(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_PO_Trans_Monitoring_Result>("[fmisEntities].[ufn_PO_Trans_Monitoring](@year)", yearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_get_Transaction_byDVNO")]
        public virtual IQueryable<ufn_JEV_get_Transaction_byDVNO_Result> ufn_JEV_get_Transaction_byDVNO(string dvno)
        {
            var dvnoParameter = dvno != null ?
                new ObjectParameter("dvno", dvno) :
                new ObjectParameter("dvno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_get_Transaction_byDVNO_Result>("[fmisEntities].[ufn_JEV_get_Transaction_byDVNO](@dvno)", dvnoParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_get_jev_sub_byDVNO")]
        public virtual IQueryable<ufn_JEV_get_jev_sub_byDVNO_Result> ufn_JEV_get_jev_sub_byDVNO(string reffno, Nullable<int> accountChildParentID, Nullable<int> gLAccountChildParentID)
        {
            var reffnoParameter = reffno != null ?
                new ObjectParameter("reffno", reffno) :
                new ObjectParameter("reffno", typeof(string));
    
            var accountChildParentIDParameter = accountChildParentID.HasValue ?
                new ObjectParameter("AccountChildParentID", accountChildParentID) :
                new ObjectParameter("AccountChildParentID", typeof(int));
    
            var gLAccountChildParentIDParameter = gLAccountChildParentID.HasValue ?
                new ObjectParameter("GLAccountChildParentID", gLAccountChildParentID) :
                new ObjectParameter("GLAccountChildParentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_get_jev_sub_byDVNO_Result>("[fmisEntities].[ufn_JEV_get_jev_sub_byDVNO](@reffno, @AccountChildParentID, @GLAccountChildParentID)", reffnoParameter, accountChildParentIDParameter, gLAccountChildParentIDParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_get_jev_byDVNO")]
        public virtual IQueryable<ufn_JEV_get_jev_byDVNO_Result> ufn_JEV_get_jev_byDVNO(string reffno)
        {
            var reffnoParameter = reffno != null ?
                new ObjectParameter("reffno", reffno) :
                new ObjectParameter("reffno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_get_jev_byDVNO_Result>("[fmisEntities].[ufn_JEV_get_jev_byDVNO](@reffno)", reffnoParameter);
        }
    
        public virtual int usp_jev_delete_GLEntries(string reffno, Nullable<int> gLparentID)
        {
            var reffnoParameter = reffno != null ?
                new ObjectParameter("reffno", reffno) :
                new ObjectParameter("reffno", typeof(string));
    
            var gLparentIDParameter = gLparentID.HasValue ?
                new ObjectParameter("GLparentID", gLparentID) :
                new ObjectParameter("GLparentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_jev_delete_GLEntries", reffnoParameter, gLparentIDParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_get_transaction_byDate")]
        public virtual IQueryable<ufn_JEV_get_transaction_byDate_Result> ufn_JEV_get_transaction_byDate(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_get_transaction_byDate_Result>("[fmisEntities].[ufn_JEV_get_transaction_byDate](@from, @to)", fromParameter, toParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_transaction_liquidation_byDate")]
        public virtual IQueryable<ufn_JEV_transaction_liquidation_byDate_Result> ufn_JEV_transaction_liquidation_byDate(Nullable<System.DateTime> from, Nullable<System.DateTime> to, string userid)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_transaction_liquidation_byDate_Result>("[fmisEntities].[ufn_JEV_transaction_liquidation_byDate](@from, @to, @userid)", fromParameter, toParameter, useridParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_ComboSource_AccountToChange")]
        public virtual IQueryable<ufn_ComboSource_AccountToChange_Result> ufn_ComboSource_AccountToChange(string parentcode)
        {
            var parentcodeParameter = parentcode != null ?
                new ObjectParameter("parentcode", parentcode) :
                new ObjectParameter("parentcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_ComboSource_AccountToChange_Result>("[fmisEntities].[ufn_ComboSource_AccountToChange](@parentcode)", parentcodeParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_ComboSource_ClaimantType")]
        public virtual IQueryable<ufn_ComboSource_ClaimantType_Result> ufn_ComboSource_ClaimantType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_ComboSource_ClaimantType_Result>("[fmisEntities].[ufn_ComboSource_ClaimantType]()");
        }
    
        [DbFunction("fmisEntities", "ufn_get_payrollOfficeBatchno")]
        public virtual IQueryable<ufn_get_payrollOfficeBatchno_Result> ufn_get_payrollOfficeBatchno(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_get_payrollOfficeBatchno_Result>("[fmisEntities].[ufn_get_payrollOfficeBatchno](@month, @year)", monthParameter, yearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_Entries_consolidated")]
        public virtual IQueryable<ufn_JEV_Entries_consolidated_Result> ufn_JEV_Entries_consolidated(Nullable<int> jevid)
        {
            var jevidParameter = jevid.HasValue ?
                new ObjectParameter("jevid", jevid) :
                new ObjectParameter("jevid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_Entries_consolidated_Result>("[fmisEntities].[ufn_JEV_Entries_consolidated](@jevid)", jevidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Fund")]
        public virtual IQueryable<ufn_Fund_Result> ufn_Fund(Nullable<int> fundid)
        {
            var fundidParameter = fundid.HasValue ?
                new ObjectParameter("fundid", fundid) :
                new ObjectParameter("fundid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Fund_Result>("[fmisEntities].[ufn_Fund](@fundid)", fundidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Journals_Recap_byDate")]
        public virtual IQueryable<ufn_Journals_Recap_byDate_Result> ufn_Journals_Recap_byDate(Nullable<System.DateTime> from, Nullable<System.DateTime> to, string userid, Nullable<int> journalTypeid, Nullable<int> fundid)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var journalTypeidParameter = journalTypeid.HasValue ?
                new ObjectParameter("journalTypeid", journalTypeid) :
                new ObjectParameter("journalTypeid", typeof(int));
    
            var fundidParameter = fundid.HasValue ?
                new ObjectParameter("fundid", fundid) :
                new ObjectParameter("fundid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Journals_Recap_byDate_Result>("[fmisEntities].[ufn_Journals_Recap_byDate](@from, @to, @userid, @journalTypeid, @fundid)", fromParameter, toParameter, useridParameter, journalTypeidParameter, fundidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Ledger_Subsidiary_GL_byDate")]
        public virtual IQueryable<ufn_Ledger_Subsidiary_GL_byDate_Result> ufn_Ledger_Subsidiary_GL_byDate(Nullable<long> iD, Nullable<System.DateTime> from, Nullable<System.DateTime> to, Nullable<int> fundid)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var fundidParameter = fundid.HasValue ?
                new ObjectParameter("fundid", fundid) :
                new ObjectParameter("fundid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Ledger_Subsidiary_GL_byDate_Result>("[fmisEntities].[ufn_Ledger_Subsidiary_GL_byDate](@ID, @from, @to, @fundid)", iDParameter, fromParameter, toParameter, fundidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_CashFlow_entry")]
        public virtual IQueryable<ufn_JEV_CashFlow_entry_Result> ufn_JEV_CashFlow_entry(Nullable<long> jevid)
        {
            var jevidParameter = jevid.HasValue ?
                new ObjectParameter("jevid", jevid) :
                new ObjectParameter("jevid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_CashFlow_entry_Result>("[fmisEntities].[ufn_JEV_CashFlow_entry](@jevid)", jevidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_NoCashFlow_entry")]
        public virtual IQueryable<ufn_JEV_NoCashFlow_entry_Result> ufn_JEV_NoCashFlow_entry(Nullable<int> year, Nullable<int> month)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_NoCashFlow_entry_Result>("[fmisEntities].[ufn_JEV_NoCashFlow_entry](@year, @month)", yearParameter, monthParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_RF_CashFlow_TrialBalance")]
        public virtual IQueryable<ufn_RF_CashFlow_TrialBalance_Result> ufn_RF_CashFlow_TrialBalance(Nullable<int> code, Nullable<System.DateTime> to)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_RF_CashFlow_TrialBalance_Result>("[fmisEntities].[ufn_RF_CashFlow_TrialBalance](@code, @to)", codeParameter, toParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_ComboSource_Accountname_payrollMapped")]
        public virtual IQueryable<ufn_ComboSource_Accountname_payrollMapped_Result> ufn_ComboSource_Accountname_payrollMapped(Nullable<int> payrollType)
        {
            var payrollTypeParameter = payrollType.HasValue ?
                new ObjectParameter("PayrollType", payrollType) :
                new ObjectParameter("PayrollType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_ComboSource_Accountname_payrollMapped_Result>("[fmisEntities].[ufn_ComboSource_Accountname_payrollMapped](@PayrollType)", payrollTypeParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_ComboSource_Accountname_payrollMapped_JOCOS")]
        public virtual IQueryable<ufn_ComboSource_Accountname_payrollMapped_JOCOS_Result> ufn_ComboSource_Accountname_payrollMapped_JOCOS(Nullable<int> payrollType)
        {
            var payrollTypeParameter = payrollType.HasValue ?
                new ObjectParameter("PayrollType", payrollType) :
                new ObjectParameter("PayrollType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_ComboSource_Accountname_payrollMapped_JOCOS_Result>("[fmisEntities].[ufn_ComboSource_Accountname_payrollMapped_JOCOS](@PayrollType)", payrollTypeParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_ComboSource_Accountname_payrollMapped_regular")]
        public virtual IQueryable<ufn_ComboSource_Accountname_payrollMapped_regular_Result> ufn_ComboSource_Accountname_payrollMapped_regular(Nullable<int> payrollType)
        {
            var payrollTypeParameter = payrollType.HasValue ?
                new ObjectParameter("PayrollType", payrollType) :
                new ObjectParameter("PayrollType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_ComboSource_Accountname_payrollMapped_regular_Result>("[fmisEntities].[ufn_ComboSource_Accountname_payrollMapped_regular](@PayrollType)", payrollTypeParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Ledger_Subsidiary_byDate_v1")]
        public virtual IQueryable<ufn_Ledger_Subsidiary_byDate_v1_Result> ufn_Ledger_Subsidiary_byDate_v1(Nullable<long> iD, Nullable<System.DateTime> from, Nullable<System.DateTime> to, Nullable<int> fundid, Nullable<int> nm)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var fundidParameter = fundid.HasValue ?
                new ObjectParameter("fundid", fundid) :
                new ObjectParameter("fundid", typeof(int));
    
            var nmParameter = nm.HasValue ?
                new ObjectParameter("nm", nm) :
                new ObjectParameter("nm", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Ledger_Subsidiary_byDate_v1_Result>("[fmisEntities].[ufn_Ledger_Subsidiary_byDate_v1](@ID, @from, @to, @fundid, @nm)", iDParameter, fromParameter, toParameter, fundidParameter, nmParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_cdj_getRCI")]
        public virtual IQueryable<ufn_JEV_cdj_getRCI_Result> ufn_JEV_cdj_getRCI(Nullable<int> fundid, Nullable<int> year, Nullable<int> month)
        {
            var fundidParameter = fundid.HasValue ?
                new ObjectParameter("fundid", fundid) :
                new ObjectParameter("fundid", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_cdj_getRCI_Result>("[fmisEntities].[ufn_JEV_cdj_getRCI](@fundid, @year, @month)", fundidParameter, yearParameter, monthParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_cdj_getRCI_details")]
        public virtual IQueryable<ufn_JEV_cdj_getRCI_details_Result> ufn_JEV_cdj_getRCI_details(string rcino)
        {
            var rcinoParameter = rcino != null ?
                new ObjectParameter("rcino", rcino) :
                new ObjectParameter("rcino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_cdj_getRCI_details_Result>("[fmisEntities].[ufn_JEV_cdj_getRCI_details](@rcino)", rcinoParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_CashJ_getFMISNO")]
        public virtual IQueryable<ufn_JEV_CashJ_getFMISNO_Result> ufn_JEV_CashJ_getFMISNO(Nullable<int> fundid, Nullable<int> year, Nullable<int> month)
        {
            var fundidParameter = fundid.HasValue ?
                new ObjectParameter("fundid", fundid) :
                new ObjectParameter("fundid", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_CashJ_getFMISNO_Result>("[fmisEntities].[ufn_JEV_CashJ_getFMISNO](@fundid, @year, @month)", fundidParameter, yearParameter, monthParameter);
        }
    
        public virtual ObjectResult<string> usp_check_refno(Nullable<int> iS_ID, string iS_reffno, string unique_refno, string particular, Nullable<decimal> amount)
        {
            var iS_IDParameter = iS_ID.HasValue ?
                new ObjectParameter("IS_ID", iS_ID) :
                new ObjectParameter("IS_ID", typeof(int));
    
            var iS_reffnoParameter = iS_reffno != null ?
                new ObjectParameter("IS_reffno", iS_reffno) :
                new ObjectParameter("IS_reffno", typeof(string));
    
            var unique_refnoParameter = unique_refno != null ?
                new ObjectParameter("Unique_refno", unique_refno) :
                new ObjectParameter("Unique_refno", typeof(string));
    
            var particularParameter = particular != null ?
                new ObjectParameter("particular", particular) :
                new ObjectParameter("particular", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_check_refno", iS_IDParameter, iS_reffnoParameter, unique_refnoParameter, particularParameter, amountParameter);
        }
    
        public virtual ObjectResult<usp_get_loghistory_Result> usp_get_loghistory(string unique_refno)
        {
            var unique_refnoParameter = unique_refno != null ?
                new ObjectParameter("Unique_refno", unique_refno) :
                new ObjectParameter("Unique_refno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_loghistory_Result>("usp_get_loghistory", unique_refnoParameter);
        }
    
        public virtual ObjectResult<usp_get_transctionInfo_Result> usp_get_transctionInfo(string unique_refno)
        {
            var unique_refnoParameter = unique_refno != null ?
                new ObjectParameter("Unique_refno", unique_refno) :
                new ObjectParameter("Unique_refno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_transctionInfo_Result>("usp_get_transctionInfo", unique_refnoParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_ComboSource_prerequisite")]
        public virtual IQueryable<ufn_ComboSource_prerequisite_Result> ufn_ComboSource_prerequisite(Nullable<int> status_code, Nullable<int> iS_id)
        {
            var status_codeParameter = status_code.HasValue ?
                new ObjectParameter("status_code", status_code) :
                new ObjectParameter("status_code", typeof(int));
    
            var iS_idParameter = iS_id.HasValue ?
                new ObjectParameter("IS_id", iS_id) :
                new ObjectParameter("IS_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_ComboSource_prerequisite_Result>("[fmisEntities].[ufn_ComboSource_prerequisite](@status_code, @IS_id)", status_codeParameter, iS_idParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_getPgasUserByEmail")]
        public virtual IQueryable<ufn_getPgasUserByEmail_Result> ufn_getPgasUserByEmail(string emailaddress)
        {
            var emailaddressParameter = emailaddress != null ?
                new ObjectParameter("emailaddress", emailaddress) :
                new ObjectParameter("emailaddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_getPgasUserByEmail_Result>("[fmisEntities].[ufn_getPgasUserByEmail](@emailaddress)", emailaddressParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Ledger_Subsidiary_byDate_test")]
        public virtual IQueryable<ufn_Ledger_Subsidiary_byDate_test_Result> ufn_Ledger_Subsidiary_byDate_test(Nullable<long> iD, Nullable<System.DateTime> from, Nullable<System.DateTime> to, Nullable<int> fundid)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var fundidParameter = fundid.HasValue ?
                new ObjectParameter("fundid", fundid) :
                new ObjectParameter("fundid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Ledger_Subsidiary_byDate_test_Result>("[fmisEntities].[ufn_Ledger_Subsidiary_byDate_test](@ID, @from, @to, @fundid)", iDParameter, fromParameter, toParameter, fundidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_grid_transaction_type")]
        public virtual IQueryable<ufn_grid_transaction_type_Result> ufn_grid_transaction_type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_grid_transaction_type_Result>("[fmisEntities].[ufn_grid_transaction_type]()");
        }
    
        [DbFunction("fmisEntities", "ufn_pmis_officename")]
        public virtual IQueryable<ufn_pmis_officename_Result> ufn_pmis_officename()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_pmis_officename_Result>("[fmisEntities].[ufn_pmis_officename]()");
        }
    
        [DbFunction("fmisEntities", "ufn_liaison_officer")]
        public virtual IQueryable<ufn_liaison_officer_Result> ufn_liaison_officer(Nullable<int> officeid)
        {
            var officeidParameter = officeid.HasValue ?
                new ObjectParameter("officeid", officeid) :
                new ObjectParameter("officeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_liaison_officer_Result>("[fmisEntities].[ufn_liaison_officer](@officeid)", officeidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_grid_tracking_list")]
        public virtual IQueryable<ufn_grid_tracking_list_Result> ufn_grid_tracking_list(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_grid_tracking_list_Result>("[fmisEntities].[ufn_grid_tracking_list](@userid)", useridParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_fmis_officename")]
        public virtual IQueryable<ufn_fmis_officename_Result> ufn_fmis_officename()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_fmis_officename_Result>("[fmisEntities].[ufn_fmis_officename]()");
        }
    
        [DbFunction("fmisEntities", "ufn_Recon_Criteria")]
        public virtual IQueryable<ufn_Recon_Criteria_Result> ufn_Recon_Criteria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Recon_Criteria_Result>("[fmisEntities].[ufn_Recon_Criteria]()");
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_get_jev_sub_byjevid")]
        public virtual IQueryable<ufn_JEV_get_jev_sub_byjevid_Result> ufn_JEV_get_jev_sub_byjevid(Nullable<int> jevid, Nullable<int> accountChildParentID, Nullable<int> gLAccountChildParentID)
        {
            var jevidParameter = jevid.HasValue ?
                new ObjectParameter("jevid", jevid) :
                new ObjectParameter("jevid", typeof(int));
    
            var accountChildParentIDParameter = accountChildParentID.HasValue ?
                new ObjectParameter("AccountChildParentID", accountChildParentID) :
                new ObjectParameter("AccountChildParentID", typeof(int));
    
            var gLAccountChildParentIDParameter = gLAccountChildParentID.HasValue ?
                new ObjectParameter("GLAccountChildParentID", gLAccountChildParentID) :
                new ObjectParameter("GLAccountChildParentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_get_jev_sub_byjevid_Result>("[fmisEntities].[ufn_JEV_get_jev_sub_byjevid](@jevid, @AccountChildParentID, @GLAccountChildParentID)", jevidParameter, accountChildParentIDParameter, gLAccountChildParentIDParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_get_jev_byjevid")]
        public virtual IQueryable<ufn_JEV_get_jev_byjevid_Result> ufn_JEV_get_jev_byjevid(Nullable<int> jevid)
        {
            var jevidParameter = jevid.HasValue ?
                new ObjectParameter("jevid", jevid) :
                new ObjectParameter("jevid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_get_jev_byjevid_Result>("[fmisEntities].[ufn_JEV_get_jev_byjevid](@jevid)", jevidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_import_accounts_payable")]
        public virtual IQueryable<ufn_JEV_import_accounts_payable_Result> ufn_JEV_import_accounts_payable(Nullable<int> fundcode, Nullable<int> year)
        {
            var fundcodeParameter = fundcode.HasValue ?
                new ObjectParameter("fundcode", fundcode) :
                new ObjectParameter("fundcode", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_import_accounts_payable_Result>("[fmisEntities].[ufn_JEV_import_accounts_payable](@fundcode, @year)", fundcodeParameter, yearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_import_postclosing")]
        public virtual IQueryable<ufn_JEV_import_postclosing_Result> ufn_JEV_import_postclosing(Nullable<int> fundcode, Nullable<int> year, Nullable<int> chartAccountID)
        {
            var fundcodeParameter = fundcode.HasValue ?
                new ObjectParameter("fundcode", fundcode) :
                new ObjectParameter("fundcode", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var chartAccountIDParameter = chartAccountID.HasValue ?
                new ObjectParameter("ChartAccountID", chartAccountID) :
                new ObjectParameter("ChartAccountID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_import_postclosing_Result>("[fmisEntities].[ufn_JEV_import_postclosing](@fundcode, @year, @ChartAccountID)", fundcodeParameter, yearParameter, chartAccountIDParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Ledger_Subsidiary_byDate")]
        public virtual IQueryable<ufn_Ledger_Subsidiary_byDate_Result> ufn_Ledger_Subsidiary_byDate(string childcode, Nullable<System.DateTime> from, Nullable<System.DateTime> to, Nullable<int> fundid, Nullable<int> nm)
        {
            var childcodeParameter = childcode != null ?
                new ObjectParameter("childcode", childcode) :
                new ObjectParameter("childcode", typeof(string));
    
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var fundidParameter = fundid.HasValue ?
                new ObjectParameter("fundid", fundid) :
                new ObjectParameter("fundid", typeof(int));
    
            var nmParameter = nm.HasValue ?
                new ObjectParameter("nm", nm) :
                new ObjectParameter("nm", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Ledger_Subsidiary_byDate_Result>("[fmisEntities].[ufn_Ledger_Subsidiary_byDate](@childcode, @from, @to, @fundid, @nm)", childcodeParameter, fromParameter, toParameter, fundidParameter, nmParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Doc_Logos")]
        public virtual IQueryable<ufn_Doc_Logos_Result> ufn_Doc_Logos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Doc_Logos_Result>("[fmisEntities].[ufn_Doc_Logos]()");
        }
    
        [DbFunction("fmisEntities", "ufn_Log_status_Description")]
        public virtual IQueryable<ufn_Log_status_Description_Result> ufn_Log_status_Description(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Log_status_Description_Result>("[fmisEntities].[ufn_Log_status_Description](@userid)", useridParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Log_status_list")]
        public virtual IQueryable<ufn_Log_status_list_Result> ufn_Log_status_list(Nullable<System.DateTime> from, Nullable<System.DateTime> to, Nullable<int> status_id)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Log_status_list_Result>("[fmisEntities].[ufn_Log_status_list](@from, @to, @status_id)", fromParameter, toParameter, status_idParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Query_RAAOU_summary")]
        public virtual IQueryable<ufn_Query_RAAOU_summary_Result> ufn_Query_RAAOU_summary(Nullable<int> year, Nullable<int> month)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Query_RAAOU_summary_Result>("[fmisEntities].[ufn_Query_RAAOU_summary](@year, @Month)", yearParameter, monthParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_CashJ_getFMISNO_details")]
        public virtual IQueryable<ufn_JEV_CashJ_getFMISNO_details_Result> ufn_JEV_CashJ_getFMISNO_details(string recordID)
        {
            var recordIDParameter = recordID != null ?
                new ObjectParameter("RecordID", recordID) :
                new ObjectParameter("RecordID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_CashJ_getFMISNO_details_Result>("[fmisEntities].[ufn_JEV_CashJ_getFMISNO_details](@RecordID)", recordIDParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_JEV_CashR_byPTVNo")]
        public virtual IQueryable<ufn_JEV_CashR_byPTVNo_Result> ufn_JEV_CashR_byPTVNo(Nullable<int> fundid, Nullable<int> year, Nullable<int> month)
        {
            var fundidParameter = fundid.HasValue ?
                new ObjectParameter("fundid", fundid) :
                new ObjectParameter("fundid", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_JEV_CashR_byPTVNo_Result>("[fmisEntities].[ufn_JEV_CashR_byPTVNo](@fundid, @year, @month)", fundidParameter, yearParameter, monthParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Expense_details")]
        public virtual IQueryable<ufn_Expense_details_Result> ufn_Expense_details(Nullable<int> dvid)
        {
            var dvidParameter = dvid.HasValue ?
                new ObjectParameter("dvid", dvid) :
                new ObjectParameter("dvid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Expense_details_Result>("[fmisEntities].[ufn_Expense_details](@dvid)", dvidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_SAAOD_obligation_summary_ByOffice")]
        public virtual IQueryable<ufn_SAAOD_obligation_summary_ByOffice_Result> ufn_SAAOD_obligation_summary_ByOffice(Nullable<int> yearof, Nullable<int> monthof, Nullable<int> officeid)
        {
            var yearofParameter = yearof.HasValue ?
                new ObjectParameter("Yearof", yearof) :
                new ObjectParameter("Yearof", typeof(int));
    
            var monthofParameter = monthof.HasValue ?
                new ObjectParameter("monthof", monthof) :
                new ObjectParameter("monthof", typeof(int));
    
            var officeidParameter = officeid.HasValue ?
                new ObjectParameter("officeid", officeid) :
                new ObjectParameter("officeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_SAAOD_obligation_summary_ByOffice_Result>("[fmisEntities].[ufn_SAAOD_obligation_summary_ByOffice](@Yearof, @monthof, @officeid)", yearofParameter, monthofParameter, officeidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Oblig_grid_RAAU")]
        public virtual IQueryable<ufn_Oblig_grid_RAAU_Result> ufn_Oblig_grid_RAAU(Nullable<int> monthof, Nullable<int> yearof, Nullable<int> officeid)
        {
            var monthofParameter = monthof.HasValue ?
                new ObjectParameter("monthof", monthof) :
                new ObjectParameter("monthof", typeof(int));
    
            var yearofParameter = yearof.HasValue ?
                new ObjectParameter("yearof", yearof) :
                new ObjectParameter("yearof", typeof(int));
    
            var officeidParameter = officeid.HasValue ?
                new ObjectParameter("officeid", officeid) :
                new ObjectParameter("officeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Oblig_grid_RAAU_Result>("[fmisEntities].[ufn_Oblig_grid_RAAU](@monthof, @yearof, @officeid)", monthofParameter, yearofParameter, officeidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Oblig_Expense_grid")]
        public virtual IQueryable<ufn_Oblig_Expense_grid_Result> ufn_Oblig_Expense_grid(Nullable<int> obligID)
        {
            var obligIDParameter = obligID.HasValue ?
                new ObjectParameter("obligID", obligID) :
                new ObjectParameter("obligID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Oblig_Expense_grid_Result>("[fmisEntities].[ufn_Oblig_Expense_grid](@obligID)", obligIDParameter);
        }
    
        [DbFunction("fmisEntities", "fn_Oblig_cmb_accountname")]
        public virtual IQueryable<fn_Oblig_cmb_accountname_Result> fn_Oblig_cmb_accountname(Nullable<short> officeid, Nullable<int> year)
        {
            var officeidParameter = officeid.HasValue ?
                new ObjectParameter("officeid", officeid) :
                new ObjectParameter("officeid", typeof(short));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Oblig_cmb_accountname_Result>("[fmisEntities].[fn_Oblig_cmb_accountname](@officeid, @year)", officeidParameter, yearParameter);
        }
    
        [DbFunction("fmisEntities", "fn_Oblig_Accountname")]
        public virtual IQueryable<fn_Oblig_Accountname_Result> fn_Oblig_Accountname(Nullable<short> officeid, Nullable<int> year)
        {
            var officeidParameter = officeid.HasValue ?
                new ObjectParameter("officeid", officeid) :
                new ObjectParameter("officeid", typeof(short));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Oblig_Accountname_Result>("[fmisEntities].[fn_Oblig_Accountname](@officeid, @year)", officeidParameter, yearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_oblig_transaction_grid")]
        public virtual IQueryable<ufn_oblig_transaction_grid_Result> ufn_oblig_transaction_grid(Nullable<int> year, Nullable<int> monthof, Nullable<int> officeid)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthofParameter = monthof.HasValue ?
                new ObjectParameter("monthof", monthof) :
                new ObjectParameter("monthof", typeof(int));
    
            var officeidParameter = officeid.HasValue ?
                new ObjectParameter("officeid", officeid) :
                new ObjectParameter("officeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_oblig_transaction_grid_Result>("[fmisEntities].[ufn_oblig_transaction_grid](@year, @monthof, @officeid)", yearParameter, monthofParameter, officeidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Query_RAAOU_bySector")]
        public virtual IQueryable<ufn_Query_RAAOU_bySector_Result> ufn_Query_RAAOU_bySector(Nullable<int> monthof, Nullable<int> yearof)
        {
            var monthofParameter = monthof.HasValue ?
                new ObjectParameter("monthof", monthof) :
                new ObjectParameter("monthof", typeof(int));
    
            var yearofParameter = yearof.HasValue ?
                new ObjectParameter("yearof", yearof) :
                new ObjectParameter("yearof", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Query_RAAOU_bySector_Result>("[fmisEntities].[ufn_Query_RAAOU_bySector](@monthof, @yearof)", monthofParameter, yearofParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_chartOfAccounts_expenses")]
        public virtual IQueryable<ufn_chartOfAccounts_expenses_Result> ufn_chartOfAccounts_expenses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_chartOfAccounts_expenses_Result>("[fmisEntities].[ufn_chartOfAccounts_expenses]()");
        }
    
        [DbFunction("fmisEntities", "ufn_expenses_byyear")]
        public virtual IQueryable<ufn_expenses_byyear_Result> ufn_expenses_byyear(Nullable<int> toyear)
        {
            var toyearParameter = toyear.HasValue ?
                new ObjectParameter("toyear", toyear) :
                new ObjectParameter("toyear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_expenses_byyear_Result>("[fmisEntities].[ufn_expenses_byyear](@toyear)", toyearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_expenses_byyear_details")]
        public virtual IQueryable<ufn_expenses_byyear_details_Result> ufn_expenses_byyear_details(Nullable<int> year, Nullable<int> rcenterid, string childcode)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var rcenteridParameter = rcenterid.HasValue ?
                new ObjectParameter("rcenterid", rcenterid) :
                new ObjectParameter("rcenterid", typeof(int));
    
            var childcodeParameter = childcode != null ?
                new ObjectParameter("childcode", childcode) :
                new ObjectParameter("childcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_expenses_byyear_details_Result>("[fmisEntities].[ufn_expenses_byyear_details](@year, @rcenterid, @childcode)", yearParameter, rcenteridParameter, childcodeParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_fmis_officename_byYear")]
        public virtual IQueryable<ufn_fmis_officename_byYear_Result> ufn_fmis_officename_byYear(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_fmis_officename_byYear_Result>("[fmisEntities].[ufn_fmis_officename_byYear](@year)", yearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_expenses_byyear_cbms")]
        public virtual IQueryable<ufn_expenses_byyear_cbms_Result> ufn_expenses_byyear_cbms(Nullable<int> toyear)
        {
            var toyearParameter = toyear.HasValue ?
                new ObjectParameter("toyear", toyear) :
                new ObjectParameter("toyear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_expenses_byyear_cbms_Result>("[fmisEntities].[ufn_expenses_byyear_cbms](@toyear)", toyearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_expenses_byyear_printing_publication")]
        public virtual IQueryable<ufn_expenses_byyear_printing_publication_Result> ufn_expenses_byyear_printing_publication(Nullable<int> toyear)
        {
            var toyearParameter = toyear.HasValue ?
                new ObjectParameter("toyear", toyear) :
                new ObjectParameter("toyear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_expenses_byyear_printing_publication_Result>("[fmisEntities].[ufn_expenses_byyear_printing_publication](@toyear)", toyearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_expenses_byyear_details_cbms")]
        public virtual IQueryable<ufn_expenses_byyear_details_cbms_Result> ufn_expenses_byyear_details_cbms(Nullable<int> year, Nullable<int> rcenterid, string childcode)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var rcenteridParameter = rcenterid.HasValue ?
                new ObjectParameter("rcenterid", rcenterid) :
                new ObjectParameter("rcenterid", typeof(int));
    
            var childcodeParameter = childcode != null ?
                new ObjectParameter("childcode", childcode) :
                new ObjectParameter("childcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_expenses_byyear_details_cbms_Result>("[fmisEntities].[ufn_expenses_byyear_details_cbms](@year, @rcenterid, @childcode)", yearParameter, rcenteridParameter, childcodeParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_expenses_byyear_details_printing_publication")]
        public virtual IQueryable<ufn_expenses_byyear_details_printing_publication_Result> ufn_expenses_byyear_details_printing_publication(Nullable<int> year, Nullable<int> rcenterid, string childcode)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var rcenteridParameter = rcenterid.HasValue ?
                new ObjectParameter("rcenterid", rcenterid) :
                new ObjectParameter("rcenterid", typeof(int));
    
            var childcodeParameter = childcode != null ?
                new ObjectParameter("childcode", childcode) :
                new ObjectParameter("childcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_expenses_byyear_details_printing_publication_Result>("[fmisEntities].[ufn_expenses_byyear_details_printing_publication](@year, @rcenterid, @childcode)", yearParameter, rcenteridParameter, childcodeParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_expenses_byyear_cbms_summary")]
        public virtual IQueryable<ufn_expenses_byyear_cbms_summary_Result> ufn_expenses_byyear_cbms_summary(Nullable<int> toyear)
        {
            var toyearParameter = toyear.HasValue ?
                new ObjectParameter("toyear", toyear) :
                new ObjectParameter("toyear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_expenses_byyear_cbms_summary_Result>("[fmisEntities].[ufn_expenses_byyear_cbms_summary](@toyear)", toyearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_expenses_byyear_printing_publication_summary")]
        public virtual IQueryable<ufn_expenses_byyear_printing_publication_summary_Result> ufn_expenses_byyear_printing_publication_summary(Nullable<int> toyear)
        {
            var toyearParameter = toyear.HasValue ?
                new ObjectParameter("toyear", toyear) :
                new ObjectParameter("toyear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_expenses_byyear_printing_publication_summary_Result>("[fmisEntities].[ufn_expenses_byyear_printing_publication_summary](@toyear)", toyearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_CashBookBalance_detailed")]
        public virtual IQueryable<ufn_CashBookBalance_detailed_Result> ufn_CashBookBalance_detailed(Nullable<int> isclosed, Nullable<System.DateTime> date)
        {
            var isclosedParameter = isclosed.HasValue ?
                new ObjectParameter("isclosed", isclosed) :
                new ObjectParameter("isclosed", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_CashBookBalance_detailed_Result>("[fmisEntities].[ufn_CashBookBalance_detailed](@isclosed, @date)", isclosedParameter, dateParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_COA_get_jev_byjevid")]
        public virtual IQueryable<ufn_COA_get_jev_byjevid_Result> ufn_COA_get_jev_byjevid(Nullable<int> jevid)
        {
            var jevidParameter = jevid.HasValue ?
                new ObjectParameter("jevid", jevid) :
                new ObjectParameter("jevid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_COA_get_jev_byjevid_Result>("[fmisEntities].[ufn_COA_get_jev_byjevid](@jevid)", jevidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Treasury_fundtype")]
        public virtual IQueryable<ufn_Treasury_fundtype_Result> ufn_Treasury_fundtype()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Treasury_fundtype_Result>("[fmisEntities].[ufn_Treasury_fundtype]()");
        }
    
        [DbFunction("fmisEntities", "ufn_fundtype")]
        public virtual IQueryable<ufn_fundtype_Result> ufn_fundtype()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_fundtype_Result>("[fmisEntities].[ufn_fundtype]()");
        }
    
        [DbFunction("fmisEntities", "ufn_CashBook_Accounts")]
        public virtual IQueryable<ufn_CashBook_Accounts_Result> ufn_CashBook_Accounts(Nullable<int> fundid, Nullable<int> year, Nullable<int> month)
        {
            var fundidParameter = fundid.HasValue ?
                new ObjectParameter("fundid", fundid) :
                new ObjectParameter("fundid", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_CashBook_Accounts_Result>("[fmisEntities].[ufn_CashBook_Accounts](@fundid, @year, @month)", fundidParameter, yearParameter, monthParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Incoming_Grid")]
        public virtual IQueryable<ufn_Incoming_Grid_Result> ufn_Incoming_Grid(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Incoming_Grid_Result>("[fmisEntities].[ufn_Incoming_Grid](@year)", yearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_fmisPmis_byEID")]
        public virtual IQueryable<ufn_fmisPmis_byEID_Result> ufn_fmisPmis_byEID(Nullable<int> eid)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_fmisPmis_byEID_Result>("[fmisEntities].[ufn_fmisPmis_byEID](@eid)", eidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_WFP_details")]
        public virtual IQueryable<ufn_WFP_details_Result> ufn_WFP_details(Nullable<int> year, Nullable<int> officeid)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var officeidParameter = officeid.HasValue ?
                new ObjectParameter("officeid", officeid) :
                new ObjectParameter("officeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_WFP_details_Result>("[fmisEntities].[ufn_WFP_details](@year, @officeid)", yearParameter, officeidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_ReportName")]
        public virtual IQueryable<ufn_ReportName_Result> ufn_ReportName(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_ReportName_Result>("[fmisEntities].[ufn_ReportName](@userid)", useridParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_WFP_details_new")]
        public virtual IQueryable<ufn_WFP_details_new_Result> ufn_WFP_details_new(Nullable<int> year, Nullable<int> officeid)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var officeidParameter = officeid.HasValue ?
                new ObjectParameter("officeid", officeid) :
                new ObjectParameter("officeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_WFP_details_new_Result>("[fmisEntities].[ufn_WFP_details_new](@year, @officeid)", yearParameter, officeidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_Status_DescriptionByUser")]
        public virtual IQueryable<ufn_Status_DescriptionByUser_Result> ufn_Status_DescriptionByUser(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_Status_DescriptionByUser_Result>("[fmisEntities].[ufn_Status_DescriptionByUser](@userid)", useridParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_venue")]
        public virtual IQueryable<ufn_venue_Result> ufn_venue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_venue_Result>("[fmisEntities].[ufn_venue]()");
        }
    
        [DbFunction("fmisEntities", "ufn_recommending_officer")]
        public virtual IQueryable<ufn_recommending_officer_Result> ufn_recommending_officer(Nullable<int> officeid)
        {
            var officeidParameter = officeid.HasValue ?
                new ObjectParameter("officeid", officeid) :
                new ObjectParameter("officeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_recommending_officer_Result>("[fmisEntities].[ufn_recommending_officer](@officeid)", officeidParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_fmisPmis_byID")]
        public virtual IQueryable<ufn_fmisPmis_byID_Result> ufn_fmisPmis_byID(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_fmisPmis_byID_Result>("[fmisEntities].[ufn_fmisPmis_byID](@ID)", iDParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_WFP_details_2024")]
        public virtual IQueryable<ufn_WFP_details_2024_Result> ufn_WFP_details_2024(Nullable<int> specificActivityID, string specificactivity, Nullable<int> year)
        {
            var specificActivityIDParameter = specificActivityID.HasValue ?
                new ObjectParameter("specificActivityID", specificActivityID) :
                new ObjectParameter("specificActivityID", typeof(int));
    
            var specificactivityParameter = specificactivity != null ?
                new ObjectParameter("specificactivity", specificactivity) :
                new ObjectParameter("specificactivity", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_WFP_details_2024_Result>("[fmisEntities].[ufn_WFP_details_2024](@specificActivityID, @specificactivity, @year)", specificActivityIDParameter, specificactivityParameter, yearParameter);
        }
    
        [DbFunction("fmisEntities", "ufn_WFP_items")]
        public virtual IQueryable<ufn_WFP_items_Result> ufn_WFP_items(Nullable<int> specificActivityID, string specificactivity, Nullable<int> year)
        {
            var specificActivityIDParameter = specificActivityID.HasValue ?
                new ObjectParameter("specificActivityID", specificActivityID) :
                new ObjectParameter("specificActivityID", typeof(int));
    
            var specificactivityParameter = specificactivity != null ?
                new ObjectParameter("specificactivity", specificactivity) :
                new ObjectParameter("specificactivity", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_WFP_items_Result>("[fmisEntities].[ufn_WFP_items](@specificActivityID, @specificactivity, @year)", specificActivityIDParameter, specificactivityParameter, yearParameter);
        }
    }
}
