//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ifmisEntities : DbContext
    {
        public ifmisEntities()
            : base("name=ifmisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_B_ProjectEstimatedCost> tbl_B_ProjectEstimatedCost { get; set; }
        public virtual DbSet<tbl_Budget_ObligationPreparation> tbl_Budget_ObligationPreparation { get; set; }
        public virtual DbSet<tbl_reff_Project> tbl_reff_Project { get; set; }
        public virtual DbSet<tbl_reff_Project_mechanism> tbl_reff_Project_mechanism { get; set; }
        public virtual DbSet<tbl_reff_Project_programType> tbl_reff_Project_programType { get; set; }
        public virtual DbSet<tbl_reff_ProjectCostType> tbl_reff_ProjectCostType { get; set; }
        public virtual DbSet<tbl_reff_SignatoryType> tbl_reff_SignatoryType { get; set; }
        public virtual DbSet<tbl_reff_SourceOfFund> tbl_reff_SourceOfFund { get; set; }
        public virtual DbSet<tbl_reff_TransactionType> tbl_reff_TransactionType { get; set; }
        public virtual DbSet<tbl_reff_Fund> tbl_reff_Fund { get; set; }
        public virtual DbSet<tbl_reff_motherCOA> tbl_reff_motherCOA { get; set; }
        public virtual DbSet<vw_projectEstimatedCost> vw_projectEstimatedCost { get; set; }
        public virtual DbSet<vw_ProjectRecapDetails> vw_ProjectRecapDetails { get; set; }
        public virtual DbSet<vw_Project_grid> vw_Project_grid { get; set; }
    }
}
