//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pmisEntities : DbContext
    {
        public pmisEntities()
            : base("name=pmisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_t_Special_Payroll> tbl_t_Special_Payroll { get; set; }
        public virtual DbSet<tbl_t_Special_Payroll_batch> tbl_t_Special_Payroll_batch { get; set; }
        public virtual DbSet<tbl_t_Special_Payroll_col> tbl_t_Special_Payroll_col { get; set; }
        public virtual DbSet<tbl_t_Special_Payroll_Deduction> tbl_t_Special_Payroll_Deduction { get; set; }
        public virtual DbSet<tbl_l_Compensation> tbl_l_Compensation { get; set; }
        public virtual DbSet<tbl_l_Compensation_Column> tbl_l_Compensation_Column { get; set; }
        public virtual DbSet<tbl_Attachment> tbl_Attachment { get; set; }
    }
}
