//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_JEV_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_t_JEV_Details()
        {
            this.tbl_t_AccoutingEntries = new HashSet<tbl_t_AccoutingEntries>();
        }
    
        public long jevid { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public string RCI { get; set; }
        public string Checkno { get; set; }
        public string Particular { get; set; }
        public string JEVno { get; set; }
        public string Claimantcode { get; set; }
        public Nullable<decimal> Gamount { get; set; }
        public Nullable<int> Transtype { get; set; }
        public string FmisVoucherno { get; set; }
        public string Dvno { get; set; }
        public string Obrno { get; set; }
        public Nullable<int> RCenter { get; set; }
        public Nullable<System.DateTime> DateTimeEntered { get; set; }
        public string Rdono { get; set; }
        public string refno { get; set; }
        public Nullable<short> OOE { get; set; }
        public Nullable<System.DateTime> Jevdate { get; set; }
        public string Ptvno { get; set; }
        public Nullable<long> JevSeriesNo { get; set; }
        public string JEVby { get; set; }
        public Nullable<int> bankmatch { get; set; }
        public Nullable<int> filterInCashflow { get; set; }
        public Nullable<int> Posted { get; set; }
        public string Postedby { get; set; }
        public Nullable<System.DateTime> PostedDTE { get; set; }
        public Nullable<bool> PClosing { get; set; }
        public Nullable<byte> HaveDoc { get; set; }
        public Nullable<long> JevNoKey { get; set; }
        public Nullable<byte> isContinuing { get; set; }
        public Nullable<byte> isAdjustment { get; set; }
        public Nullable<byte> isCA { get; set; }
        public Nullable<bool> NoneAlobs { get; set; }
        public Nullable<bool> isMoreOBR { get; set; }
        public string obr2 { get; set; }
        public Nullable<short> fundID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_t_AccoutingEntries> tbl_t_AccoutingEntries { get; set; }
    }
}
