//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_Special_Payroll_batch
    {
        public int t_compensation_batchID { get; set; }
        public Nullable<int> CompensationID { get; set; }
        public Nullable<int> yearMonth { get; set; }
        public string employmentStatusArray { get; set; }
        public string employmentStatusText { get; set; }
        public Nullable<byte> status_id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
