//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_AccoutingEntries_CashFlow
    {
        public long t_AccoutingEntries_cf_id { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<int> GLChartAccountChildID { get; set; }
        public Nullable<System.DateTime> DTE { get; set; }
        public string Changeby { get; set; }
        public Nullable<long> jevID { get; set; }
        public string Accountcode { get; set; }
    }
}
