//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reff_SignatoryType
    {
        public int SignatoryTypeID { get; set; }
        public string TypeName { get; set; }
        public string ColName { get; set; }
        public Nullable<byte> isActive { get; set; }
        public Nullable<System.DateTime> changeDate { get; set; }
        public Nullable<int> ChangerID { get; set; }
    }
}
