//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_Persons_group
    {
        public int person_group_id { get; set; }
        public string GroupName { get; set; }
        public Nullable<byte> isActive { get; set; }
        public string AbbrGroupName { get; set; }
    }
}
