//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_Compensation_Column
    {
        public int Col_id { get; set; }
        public string Col_name { get; set; }
        public string Col_description { get; set; }
        public Nullable<int> CompensationID { get; set; }
        public Nullable<byte> Datatype { get; set; }
        public Nullable<byte> isIncome { get; set; }
        public Nullable<decimal> col_width { get; set; }
        public string col_format { get; set; }
        public Nullable<byte> orderby { get; set; }
        public Nullable<byte> includeTaxAnnual { get; set; }
        public Nullable<decimal> defaultAmount { get; set; }
        public string formula { get; set; }
        public Nullable<bool> editable { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isReadOnly { get; set; }
    }
}
