//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reff_ProjectCostType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_reff_ProjectCostType()
        {
            this.tbl_B_ProjectEstimatedCost = new HashSet<tbl_B_ProjectEstimatedCost>();
            this.tbl_Budget_ObligationPreparation = new HashSet<tbl_Budget_ObligationPreparation>();
            this.tbl_reff_ProjectCostType1 = new HashSet<tbl_reff_ProjectCostType>();
        }
    
        public int projectCostID { get; set; }
        public Nullable<int> ParentProjectCostID { get; set; }
        public string ProjectCostName { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_B_ProjectEstimatedCost> tbl_B_ProjectEstimatedCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Budget_ObligationPreparation> tbl_Budget_ObligationPreparation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_reff_ProjectCostType> tbl_reff_ProjectCostType1 { get; set; }
        public virtual tbl_reff_ProjectCostType tbl_reff_ProjectCostType2 { get; set; }
    }
}
