//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_ChartOfAccountsChild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_l_ChartOfAccountsChild()
        {
            this.tbl_l_ChartOfAccountsChild1 = new HashSet<tbl_l_ChartOfAccountsChild>();
            this.tbl_t_AccoutingEntries = new HashSet<tbl_t_AccoutingEntries>();
        }
    
        public int ChartAccountChildID { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> AccountChildParentID { get; set; }
        public string AccountChildName { get; set; }
        public string ChildCode { get; set; }
        public Nullable<byte> levelNo { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> hasChild { get; set; }
        public Nullable<byte> ClaimantTypeID { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ModifiedByID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_l_ChartOfAccountsChild> tbl_l_ChartOfAccountsChild1 { get; set; }
        public virtual tbl_l_ChartOfAccountsChild tbl_l_ChartOfAccountsChild2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_t_AccoutingEntries> tbl_t_AccoutingEntries { get; set; }
    }
}
