//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_DocForm
    {
        public int doc_form_id { get; set; }
        public Nullable<int> officeId { get; set; }
        public Nullable<int> liaison_eid { get; set; }
        public string Particular { get; set; }
        public Nullable<decimal> GAmount { get; set; }
        public string refno { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DTE { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> changeby { get; set; }
    }
}
