//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_InformationSystem
    {
        public int IS_id { get; set; }
        public string is_name { get; set; }
        public string is_description { get; set; }
        public Nullable<int> year_ { get; set; }
        public Nullable<int> is_type { get; set; }
        public Nullable<int> is_status { get; set; }
        public string is_developer { get; set; }
        public string key_code { get; set; }
    }
}
