//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_DocEvents_revision
    {
        public int revision_Id { get; set; }
        public Nullable<int> officeid { get; set; }
        public Nullable<int> EventId { get; set; }
        public string DTE_from { get; set; }
        public string DTE_to { get; set; }
        public string venue_from { get; set; }
        public string venue_to { get; set; }
        public string Reason { get; set; }
        public string userid { get; set; }
        public Nullable<int> iscancel { get; set; }
    }
}
