//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Attachment
    {
        public int attach_id { get; set; }
        public string attach_name { get; set; }
        public string attach_description { get; set; }
        public Nullable<byte> IsPrerequisite { get; set; }
        public Nullable<byte> orderby { get; set; }
    }
}
