//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_AccoutingEntries
    {
        public long t_AccoutingEntries_id { get; set; }
        public string reffNo { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> credit { get; set; }
        public int ChartAccountChildID { get; set; }
        public Nullable<int> GLChartAccountChildID { get; set; }
        public Nullable<System.DateTime> DTE { get; set; }
        public string Changeby { get; set; }
        public Nullable<long> jevID { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual tbl_t_JEV_Details tbl_t_JEV_Details { get; set; }
        public virtual tbl_l_ChartOfAccountsChild tbl_l_ChartOfAccountsChild { get; set; }
    }
}
