//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_Compensation
    {
        public int compensationID { get; set; }
        public string CompensatioName { get; set; }
        public string Col_Name { get; set; }
        public Nullable<int> period { get; set; }
        public string HRSignatory { get; set; }
        public Nullable<byte> istaxable { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public Nullable<bool> NoHRSig { get; set; }
        public Nullable<bool> ViewOnUser { get; set; }
    }
}
