//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_Oblig_Transaction
    {
        public long obligID { get; set; }
        public string refno { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Particular { get; set; }
        public string Claimantcode { get; set; }
        public Nullable<short> transtype_id { get; set; }
        public string Obrno { get; set; }
        public Nullable<int> officeID { get; set; }
        public Nullable<int> programID { get; set; }
        public Nullable<int> accountID { get; set; }
        public string officeProgramAccountID { get; set; }
        public Nullable<short> fundID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DTE { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<short> countperson { get; set; }
        public string ooe { get; set; }
        public string remark { get; set; }
    }
}
