//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_DocEvents_TargetParticipants
    {
        public int ParticipantId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Participant { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<int> NoOfPax { get; set; }
    }
}
