//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_DV_Details
    {
        public long DVid { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Particular { get; set; }
        public string Claimantcode { get; set; }
        public Nullable<decimal> Gamount { get; set; }
        public Nullable<short> transtype_id { get; set; }
        public Nullable<byte> JournalType_id { get; set; }
        public string Dvno { get; set; }
        public string Obrno { get; set; }
        public Nullable<int> RCenter { get; set; }
        public Nullable<System.DateTime> DateTimeEntered { get; set; }
        public string refno { get; set; }
        public Nullable<bool> NoneAlobs { get; set; }
        public Nullable<short> fundID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DTE { get; set; }
        public Nullable<int> doc_form_id { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string remark { get; set; }
        public Nullable<short> countperson { get; set; }
        public string ooe { get; set; }
    }
}
