//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_PayrollMapped
    {
        public int trnno { get; set; }
        public Nullable<byte> PayrollType { get; set; }
        public Nullable<int> DeductionID { get; set; }
        public string childcode { get; set; }
        public Nullable<int> ChartOfAccountID { get; set; }
        public Nullable<byte> isDebit { get; set; }
        public string PayrollOrRemittanceID { get; set; }
        public Nullable<byte> PayrollEmpStatusID { get; set; }
    }
}
