//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_DocEvents_IPS
    {
        public int IPS_Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public string DTE { get; set; }
        public string Activity { get; set; }
        public string AssignPerson { get; set; }
        public string userid { get; set; }
        public Nullable<bool> bold { get; set; }
        public Nullable<short> orderby { get; set; }
    }
}
