//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reff_TransactionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_reff_TransactionType()
        {
            this.tbl_Budget_ObligationPreparation = new HashSet<tbl_Budget_ObligationPreparation>();
        }
    
        public int TransactionTypeID { get; set; }
        public string TransactionTypeName { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string PartialName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Budget_ObligationPreparation> tbl_Budget_ObligationPreparation { get; set; }
    }
}
