//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_RAAOUP
    {
        public int trnno { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string OfficeName { get; set; }
        public string AccountName { get; set; }
        public string programName { get; set; }
        public Nullable<decimal> Appropropriation { get; set; }
        public Nullable<decimal> Allotment { get; set; }
        public Nullable<decimal> Obligation { get; set; }
        public Nullable<decimal> Utilization { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public Nullable<decimal> PayableUtilization { get; set; }
        public Nullable<short> month_ { get; set; }
        public Nullable<short> year { get; set; }
        public Nullable<int> DTE { get; set; }
        public Nullable<decimal> originalAmount { get; set; }
        public Nullable<decimal> supplementalAmount { get; set; }
        public Nullable<short> amount2ndType { get; set; }
    }
}
