//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_report_Signatory
    {
        public string BudgetName { get; set; }
        public string BudgetPosition { get; set; }
        public string AccountingName { get; set; }
        public string AccountingPosition { get; set; }
        public string PTOName { get; set; }
        public string PTOPosition { get; set; }
        public string HRName { get; set; }
        public string HRPosition { get; set; }
        public string LCEName { get; set; }
        public string LCEPosition { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public int UserID { get; set; }
    }
}
