//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_DocEvents_BudgetaryRequirements
    {
        public int BudgetId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Particular { get; set; }
        public string item_names { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<decimal> item_qty { get; set; }
        public Nullable<decimal> item_price { get; set; }
        public Nullable<decimal> OrginalPrice { get; set; }
        public Nullable<decimal> OriginalQty { get; set; }
    }
}
