//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_Special_Payroll_Deduction
    {
        public int special_payroll_deductionID { get; set; }
        public Nullable<int> eid { get; set; }
        public Nullable<int> CompensationID { get; set; }
        public Nullable<int> Batchno { get; set; }
        public Nullable<int> year_ { get; set; }
        public Nullable<byte> month_ { get; set; }
        public Nullable<int> Deduction_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DTE { get; set; }
        public Nullable<int> user_eid { get; set; }
    }
}
