//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_ChartOfAccountsParent
    {
        public int ChartAccountID { get; set; }
        public string Code { get; set; }
        public string ChartAccountParentID { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public Nullable<byte> NormalBalance { get; set; }
        public Nullable<byte> LevelNo { get; set; }
        public string AccountCode { get; set; }
        public string ChartAccountCode { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
    }
}
