//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Budget_ObligationPreparation
    {
        public long ObligID { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public string Obrno { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public string particulars { get; set; }
        public Nullable<int> Rcenter { get; set; }
        public Nullable<System.DateTime> DateObligated { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> projectID { get; set; }
        public Nullable<int> projectCostID { get; set; }
        public Nullable<int> fundcode { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LogDetails { get; set; }
    
        public virtual tbl_reff_Project tbl_reff_Project { get; set; }
        public virtual tbl_reff_ProjectCostType tbl_reff_ProjectCostType { get; set; }
        public virtual tbl_reff_TransactionType tbl_reff_TransactionType { get; set; }
    }
}
