//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_DocEvents
    {
        public int EventId { get; set; }
        public string Title { get; set; }
        public string InclusiveDate { get; set; }
        public string Venue { get; set; }
        public string Rationale { get; set; }
        public string Objectives { get; set; }
        public string LObjectives { get; set; }
        public string WAObjectives { get; set; }
        public string RObjectives { get; set; }
        public string ExpectedOutput { get; set; }
        public string Evaluation { get; set; }
        public string SourceOfFund { get; set; }
        public string Caterer { get; set; }
        public string addCustom { get; set; }
        public Nullable<short> EventType { get; set; }
        public string Methodology { get; set; }
        public Nullable<int> VenueID { get; set; }
        public Nullable<int> SpecificActivity_id { get; set; }
    }
}
