//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reff_Fund
    {
        public int FundID { get; set; }
        public Nullable<int> ParentFundID { get; set; }
        public int Fundcode { get; set; }
        public string Fundname { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Display { get; set; }
    }
}
