//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_Transaction_CheckList
    {
        public short checklist_id { get; set; }
        public string CheckListName { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> Transtype_id { get; set; }
    }
}
