//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_B_ProjectEstimatedCost
    {
        public int ProjectEstimatedCostID { get; set; }
        public Nullable<int> fundID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProjectCostID { get; set; }
        public Nullable<decimal> EstimatedAmount { get; set; }
        public Nullable<byte> Tranche { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tbl_reff_Project tbl_reff_Project { get; set; }
        public virtual tbl_reff_ProjectCostType tbl_reff_ProjectCostType { get; set; }
        public virtual tbl_reff_SourceOfFund tbl_reff_SourceOfFund { get; set; }
    }
}
