//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reff_SourceOfFund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_reff_SourceOfFund()
        {
            this.tbl_B_ProjectEstimatedCost = new HashSet<tbl_B_ProjectEstimatedCost>();
            this.tbl_reff_Project = new HashSet<tbl_reff_Project>();
        }
    
        public int fundID { get; set; }
        public string SourceName { get; set; }
        public Nullable<int> fundcode { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_B_ProjectEstimatedCost> tbl_B_ProjectEstimatedCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_reff_Project> tbl_reff_Project { get; set; }
    }
}
