//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reff_motherCOA
    {
        public int ClassID { get; set; }
        public Nullable<int> motherID { get; set; }
        public string classname { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> lvl { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> source { get; set; }
    }
}
