//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_PMISOffice
    {
        public int OfficeID { get; set; }
        public string OfficeName { get; set; }
        public string OfficeAbbr { get; set; }
        public string OfficeMedium { get; set; }
        public string OfficeCode { get; set; }
        public string OfficeHead { get; set; }
        public string OfficeHeadID { get; set; }
        public string OfficeDesignation { get; set; }
        public string Fund { get; set; }
        public Nullable<int> Order { get; set; }
        public string OfficeCodeGSIS { get; set; }
        public Nullable<int> SectorCode { get; set; }
        public Nullable<bool> NationalAgency { get; set; }
        public Nullable<bool> project { get; set; }
        public Nullable<bool> locatedinCapitol { get; set; }
        public string HeadCelNo { get; set; }
        public Nullable<int> isActiveOffice { get; set; }
        public Nullable<int> Plantilla_Ordering { get; set; }
        public Nullable<int> isMain { get; set; }
        public Nullable<short> IsPhysical { get; set; }
        public string email_admin { get; set; }
        public string email_emp_grouped { get; set; }
    }
}
