//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_l_Fundtype
    {
        public short FundID { get; set; }
        public Nullable<short> ParentFundID { get; set; }
        public string FundName { get; set; }
        public string FundMedium { get; set; }
        public Nullable<byte> lvl { get; set; }
        public Nullable<byte> Actioncode { get; set; }
        public Nullable<System.DateTime> changeDate { get; set; }
        public string userID { get; set; }
        public Nullable<byte> orderby { get; set; }
        public Nullable<short> FundIDConso { get; set; }
        public Nullable<int> FundIDOblig { get; set; }
    }
}
