//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reff_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_reff_Project()
        {
            this.tbl_B_ProjectEstimatedCost = new HashSet<tbl_B_ProjectEstimatedCost>();
            this.tbl_Budget_ObligationPreparation = new HashSet<tbl_Budget_ObligationPreparation>();
        }
    
        public int projectID { get; set; }
        public Nullable<decimal> project_year { get; set; }
        public Nullable<System.DateTime> date_NADAI { get; set; }
        public Nullable<int> programTypeId { get; set; }
        public Nullable<int> mechanismId { get; set; }
        public string project_name { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> date_completion { get; set; }
        public Nullable<int> fundID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<byte> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_B_ProjectEstimatedCost> tbl_B_ProjectEstimatedCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Budget_ObligationPreparation> tbl_Budget_ObligationPreparation { get; set; }
        public virtual tbl_reff_SourceOfFund tbl_reff_SourceOfFund { get; set; }
    }
}
