//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_t_Special_Payroll_col
    {
        public int t_Compensation_col_temp_id { get; set; }
        public Nullable<int> t_compensation_tempID { get; set; }
        public Nullable<int> Compensation_col_id { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string value_str { get; set; }
    
        public virtual tbl_t_Special_Payroll tbl_t_Special_Payroll { get; set; }
    }
}
