//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reff_Project_mechanism
    {
        public int mechanismId { get; set; }
        public string mechanismName { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
