//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAMIS_Logtrans
    {
        public long trnno { get; set; }
        public string Claimantname { get; set; }
        public string Particular { get; set; }
        public Nullable<decimal> Gamount { get; set; }
        public string Dvno { get; set; }
        public string Checkno { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> DTE { get; set; }
        public int Actioncode { get; set; }
        public string UserID { get; set; }
    }
}
