//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBMS_ObjectOfExpenditures
    {
        public int OOECode { get; set; }
        public string OOEAbreviation { get; set; }
        public string OOEName { get; set; }
        public string OOENGASCode { get; set; }
    }
}
