//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREF_AIS_Offices
    {
        public int FMISOfficeID { get; set; }
        public Nullable<int> MotherOfficeID { get; set; }
        public Nullable<int> pmisOfficeID { get; set; }
        public string OfficeName { get; set; }
        public string OfficeMedium { get; set; }
        public string Abbr { get; set; }
        public string address { get; set; }
        public Nullable<short> OfficeType { get; set; }
        public Nullable<int> functionID { get; set; }
        public Nullable<byte> ReserveFlag { get; set; }
        public Nullable<bool> UnderEcoEnt { get; set; }
        public Nullable<byte> actioncode { get; set; }
        public Nullable<System.DateTime> datetimeentered { get; set; }
        public string userid { get; set; }
        public string NickName { get; set; }
        public Nullable<bool> SpecialTreat { get; set; }
    }
}
