//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AspNetUsers_details
    {
        public string Id { get; set; }
        public string SwipeId { get; set; }
        public Nullable<long> eid { get; set; }
        public string EmpName { get; set; }
        public string Position { get; set; }
        public Nullable<int> Department { get; set; }
        public string OfficeAbbr { get; set; }
        public string OfficeName { get; set; }
        public string EmailAdd { get; set; }
        public Nullable<byte> employmentstatus_id { get; set; }
        public string BirthD { get; set; }
        public string NameFML { get; set; }
        public string Status { get; set; }
        public string telephone { get; set; }
    }
}
