//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_docDetails_transaction
    {
        public int doc_details_id { get; set; }
        public Nullable<short> report_id { get; set; }
        public int dgSign_doc_id { get; set; }
        public int status_code { get; set; }
        public string refno { get; set; }
        public string report_name { get; set; }
        public string Expr1 { get; set; }
    }
}
