//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Document_Status
    {
        public int doc_details_id { get; set; }
        public Nullable<int> officeId { get; set; }
        public string Title { get; set; }
        public string refno { get; set; }
        public Nullable<short> report_id { get; set; }
        public string Status_name { get; set; }
        public string ResponsiblePerson { get; set; }
        public Nullable<int> user_eid { get; set; }
        public string startDate { get; set; }
        public string InclusiveDate { get; set; }
        public string DateOfLastStatus { get; set; }
        public string remarks { get; set; }
        public int doc_form_id { get; set; }
        public string OfficeName { get; set; }
        public int status_code { get; set; }
        public Nullable<int> SpecificActivity_id { get; set; }
    }
}
