//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Employee_Concatname
    {
        public long eid { get; set; }
        public string EmpName { get; set; }
        public string NameFML { get; set; }
        public string NameLMF { get; set; }
        public int Office { get; set; }
        public Nullable<int> PayrollOffice { get; set; }
        public Nullable<byte> cause_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public string SwipEmployeeID { get; set; }
        public long EmployeeID { get; set; }
        public Nullable<byte> empStat_id { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string mi { get; set; }
        public string Suffix { get; set; }
        public string NameLMF_DBP { get; set; }
        public string mname { get; set; }
        public string Pos_Name { get; set; }
        public string Birthdate { get; set; }
        public string BirthPlace { get; set; }
    }
}
