//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Persons
    {
        public long PersonID { get; set; }
        public string Name { get; set; }
        public string AddressName { get; set; }
        public string ContactNo { get; set; }
        public string AccountNo { get; set; }
        public string Email { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> person_group_id { get; set; }
        public Nullable<int> brgyid { get; set; }
        public string AbbrGroupName { get; set; }
        public string ClaimantCode { get; set; }
    }
}
