//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Project_grid
    {
        public Nullable<int> fundID { get; set; }
        public int projectID { get; set; }
        public string SourceName { get; set; }
        public Nullable<System.DateTime> date_NADAI { get; set; }
        public string ProgramTypeName { get; set; }
        public string project_name { get; set; }
        public string Location { get; set; }
        public string mechanismName { get; set; }
        public Nullable<int> project_year { get; set; }
        public decimal TotalReceived { get; set; }
        public Nullable<decimal> ProjectedAmount { get; set; }
        public decimal Balance { get; set; }
        public Nullable<System.DateTime> date_completion { get; set; }
    }
}
