//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_projectEstimatedCost
    {
        public int projectID { get; set; }
        public string ProjectCostName { get; set; }
        public int projectCostID { get; set; }
        public int ProjectEstimatedCostID { get; set; }
        public Nullable<decimal> EstimatedAmount { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<byte> Tranche { get; set; }
        public string trancheDesc { get; set; }
    }
}
