//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PreAudit_Trans_Monitoring
    {
        public string Dvno { get; set; }
        public string Particular { get; set; }
        public string Received { get; set; }
        public string ForAudit { get; set; }
        public string Audited { get; set; }
        public Nullable<System.DateTime> DTE { get; set; }
        public Nullable<int> Hours { get; set; }
    }
}
