//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_t_Incoming_fromBudget
    {
        public long trans_id { get; set; }
        public string AlobsNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Particulars { get; set; }
        public string FundType { get; set; }
        public Nullable<int> functionID { get; set; }
        public Nullable<long> FMISAccountCode { get; set; }
    }
}
