//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAOMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_UserMenu
    {
        public string MenuName { get; set; }
        public string MenuDescription { get; set; }
        public string IconName { get; set; }
        public string Controller { get; set; }
        public string Actions { get; set; }
        public Nullable<int> userid { get; set; }
        public int t_menu_user_id { get; set; }
        public Nullable<int> Ordering { get; set; }
        public Nullable<int> LevelOrder { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int menu_id { get; set; }
        public string userid_ID { get; set; }
    }
}
